version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-24.04
  tools:
    python: "3.12"

mkdocs:
  configuration: srcDocmkdocs.yml

# Optionally declare the Python requirements required to build your docs
python:
   install:
   - requirements: srcDoc/requirements.txt
