name: Build Documentation
  
on:
  schedule:           
    # 0 minute, 0 hour, 1st day, every month, any day of week
    - cron:  '0 0 1 * *'
  push:
    branches:
      main

jobs:
  build_documentation:
    runs-on: ubuntu-latest
    steps:
      - name: Clone GITM repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: manual.tex
          working_directory: srcDoc
      - name: Rename GITM Manual
        run: mv srcDoc/manual.pdf GITM_manual.pdf
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: GITM_manual.pdf
          retention-days: 31
