name: Format Check

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  # -------------------------------------------------------------
  # Event `pull_request`: Returns all changed pull request files.
  # --------------------------------------------------------------
  check_code_formatting:
    # NOTE:
    # - This is limited to pull_request* events and would raise an error for other events.
    # - A maximum of 3000 files can be returned.
    # - For more flexibility and no limitations see "Using local .git directory" above.

    runs-on: ubuntu-latest  # windows-latest || macos-latest
    name: Test Changed Files
    permissions:
      pull-requests: read

    steps:
      - name: Clone Formatter
        uses: actions/checkout@v4
        with: 
          repository: 'GITMCode/fprettify'
          ref: gitm-customization
          path:
            fprettify
      - name: Install formatter
        run: |
          cd fprettify
          pip install .
      - name: Clone GITM
        uses: actions/checkout@v4
        with: 
          path:
            GITM
        #   repository: 'abukowski21/GITM'
      - name: Format check entire GITM repository
        run: |
          cd GITM
          git status
          python srcPython/format_GITM.py -f
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v45
      - name: Style Guide Check Changed Files
        env:
            ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          pwd
          echo "______"
          for file in ${ALL_CHANGED_FILES}; do
            python srcPython/format_GITM.py -l -s $file
          done
