name: Test GITM

on:
  pull_request:
    branches:
        develop
        main
  workflow_run:
    workflows: [Format Check]
    types:
      - completed

jobs:
  GITM_Testing:
    runs-on: ubuntu-latest
    steps:
      - name: Install MPI (mpich)
        run: sudo apt update && sudo apt install -y mpich
      - name: Clone GITM repository
        uses: actions/checkout@v4
      - name: Run tests in srcTests/auto_test
        run: |
          cd srcTests/auto_test
          ./run_all_tests.sh
